"""añadir puntuacion a entradas_diario

Revision ID: 19bac28006ab
Revises: a6b6156454a6
Create Date: 2026-04-15 01:15:18.729607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19bac28006ab'
down_revision: Union[str, Sequence[str], None] = 'a6b6156454a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_diario', sa.Column('puntuacion', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entradas_diario', 'puntuacion')
    # ### end Alembic commands ###
