"""añadir logros

Revision ID: 7274d676df0b
Revises: bc8c354484a5
Create Date: 2026-04-20 16:07:29.955477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7274d676df0b'
down_revision: Union[str, Sequence[str], None] = 'bc8c354484a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('anio_estreno', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('entradas_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('fecha_visionado', sa.Date(), nullable=False),
    sa.Column('resena', sa.Text(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entradas_diario_id_pelicula'), 'entradas_diario', ['id_pelicula'], unique=False)
    op.create_index(op.f('ix_entradas_diario_id_usuario'), 'entradas_diario', ['id_usuario'], unique=False)
    op.create_table('listas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_publica', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listas_id_usuario'), 'listas', ['id_usuario'], unique=False)
    op.create_table('me_gusta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_pelicula', name='unique_usuario_pelicula_mg')
    )
    op.create_table('peliculas_favoritas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('orden >= 1 AND orden <= 4', name='check_orden'),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_pelicula', name='unique_usuario_pelicula_fav'),
    sa.UniqueConstraint('id_usuario', 'orden', name='unique_usuario_orden_fav')
    )
    op.create_table('seguidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_seguidor', sa.Integer(), nullable=False),
    sa.Column('id_seguido', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id_seguidor != id_seguido', name='check_no_autofollow'),
    sa.ForeignKeyConstraint(['id_seguido'], ['usuarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_seguidor'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_seguidor', 'id_seguido', name='unique_seguidor_seguido')
    )
    op.create_index(op.f('ix_seguidores_id_seguido'), 'seguidores', ['id_seguido'], unique=False)
    op.create_index(op.f('ix_seguidores_id_seguidor'), 'seguidores', ['id_seguidor'], unique=False)
    op.create_table('usuario_logros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_logro', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_logro'], ['logros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_logro')
    )
    op.create_table('vistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('puntuacion >= 1 AND puntuacion <= 10', name='check_puntuacion'),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_pelicula', name='unique_usuario_pelicula_vista')
    )
    op.create_index(op.f('ix_vistas_id_pelicula'), 'vistas', ['id_pelicula'], unique=False)
    op.create_index(op.f('ix_vistas_id_usuario'), 'vistas', ['id_usuario'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_pelicula', name='unique_usuario_pelicula_wl')
    )
    op.create_table('comentarios_resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_entrada_diario', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_entrada_diario'], ['entradas_diario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_resena_id_entrada_diario'), 'comentarios_resena', ['id_entrada_diario'], unique=False)
    op.create_table('likes_resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_entrada_diario', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_entrada_diario'], ['entradas_diario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_entrada_diario', name='unique_usuario_entrada_like')
    )
    op.create_index(op.f('ix_likes_resena_id_entrada_diario'), 'likes_resena', ['id_entrada_diario'], unique=False)
    op.create_table('listas_peliculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['listas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_pelicula'], ['peliculas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_lista', 'id_pelicula', name='unique_lista_pelicula')
    )
    op.create_index(op.f('ix_listas_peliculas_id_lista'), 'listas_peliculas', ['id_lista'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listas_peliculas_id_lista'), table_name='listas_peliculas')
    op.drop_table('listas_peliculas')
    op.drop_index(op.f('ix_likes_resena_id_entrada_diario'), table_name='likes_resena')
    op.drop_table('likes_resena')
    op.drop_index(op.f('ix_comentarios_resena_id_entrada_diario'), table_name='comentarios_resena')
    op.drop_table('comentarios_resena')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_vistas_id_usuario'), table_name='vistas')
    op.drop_index(op.f('ix_vistas_id_pelicula'), table_name='vistas')
    op.drop_table('vistas')
    op.drop_table('usuario_logros')
    op.drop_index(op.f('ix_seguidores_id_seguidor'), table_name='seguidores')
    op.drop_index(op.f('ix_seguidores_id_seguido'), table_name='seguidores')
    op.drop_table('seguidores')
    op.drop_table('peliculas_favoritas')
    op.drop_table('me_gusta')
    op.drop_index(op.f('ix_listas_id_usuario'), table_name='listas')
    op.drop_table('listas')
    op.drop_index(op.f('ix_entradas_diario_id_usuario'), table_name='entradas_diario')
    op.drop_index(op.f('ix_entradas_diario_id_pelicula'), table_name='entradas_diario')
    op.drop_table('entradas_diario')
    op.drop_table('usuarios')
    op.drop_table('peliculas')
    op.drop_table('logros')
    # ### end Alembic commands ###
