"""añadir lista-colaboración

Revision ID: 878afd394f0b
Revises: 9b5e16620609
Create Date: 2026-05-04 11:26:25.993499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '878afd394f0b'
down_revision: Union[str, Sequence[str], None] = '9b5e16620609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lista_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['listas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_lista', 'id_usuario', name='unique_lista_colaborador')
    )
    op.create_index(op.f('ix_lista_colaboradores_id_lista'), 'lista_colaboradores', ['id_lista'], unique=False)
    op.alter_column('usuario_logros', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_logros', 'id_logro',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usuario_logros', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_usuario_logros_id_logro'), 'usuario_logros', ['id_logro'], unique=False)
    op.create_index(op.f('ix_usuario_logros_id_usuario'), 'usuario_logros', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_logros_id_usuario'), table_name='usuario_logros')
    op.drop_index(op.f('ix_usuario_logros_id_logro'), table_name='usuario_logros')
    op.alter_column('usuario_logros', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('usuario_logros', 'id_logro',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usuario_logros', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_lista_colaboradores_id_lista'), table_name='lista_colaboradores')
    op.drop_table('lista_colaboradores')
    # ### end Alembic commands ###
