"""eliminar actor_favorito_id y director_favorito_id de usuarios

Revision ID: a6b6156454a6
Revises: bb6ae2860034
Create Date: 2026-04-15 00:50:17.001139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b6156454a6'
down_revision: Union[str, Sequence[str], None] = 'bb6ae2860034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'actor_favorito_id')
    op.drop_column('usuarios', 'director_favorito_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('director_favorito_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('actor_favorito_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
