"""añadir actor_favorito_id y director_favorito_id a usuarios

Revision ID: bb6ae2860034
Revises: b7e2f91a3c05
Create Date: 2026-04-15 00:36:01.051576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6ae2860034'
down_revision: Union[str, Sequence[str], None] = 'b7e2f91a3c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('actor_favorito_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('director_favorito_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'director_favorito_id')
    op.drop_column('usuarios', 'actor_favorito_id')
    # ### end Alembic commands ###
