"""añadir índices en FK críticas

Revision ID: bc8c354484a5
Revises: 19bac28006ab
Create Date: 2026-04-15 16:17:15.701990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8c354484a5'
down_revision: Union[str, Sequence[str], None] = '19bac28006ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comentarios_resena_id_entrada_diario'), 'comentarios_resena', ['id_entrada_diario'], unique=False)
    op.create_index(op.f('ix_entradas_diario_id_pelicula'), 'entradas_diario', ['id_pelicula'], unique=False)
    op.create_index(op.f('ix_entradas_diario_id_usuario'), 'entradas_diario', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_likes_resena_id_entrada_diario'), 'likes_resena', ['id_entrada_diario'], unique=False)
    op.create_index(op.f('ix_listas_id_usuario'), 'listas', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_listas_peliculas_id_lista'), 'listas_peliculas', ['id_lista'], unique=False)
    op.create_index(op.f('ix_seguidores_id_seguido'), 'seguidores', ['id_seguido'], unique=False)
    op.create_index(op.f('ix_seguidores_id_seguidor'), 'seguidores', ['id_seguidor'], unique=False)
    op.create_index(op.f('ix_vistas_id_pelicula'), 'vistas', ['id_pelicula'], unique=False)
    op.create_index(op.f('ix_vistas_id_usuario'), 'vistas', ['id_usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vistas_id_usuario'), table_name='vistas')
    op.drop_index(op.f('ix_vistas_id_pelicula'), table_name='vistas')
    op.drop_index(op.f('ix_seguidores_id_seguidor'), table_name='seguidores')
    op.drop_index(op.f('ix_seguidores_id_seguido'), table_name='seguidores')
    op.drop_index(op.f('ix_listas_peliculas_id_lista'), table_name='listas_peliculas')
    op.drop_index(op.f('ix_listas_id_usuario'), table_name='listas')
    op.drop_index(op.f('ix_likes_resena_id_entrada_diario'), table_name='likes_resena')
    op.drop_index(op.f('ix_entradas_diario_id_usuario'), table_name='entradas_diario')
    op.drop_index(op.f('ix_entradas_diario_id_pelicula'), table_name='entradas_diario')
    op.drop_index(op.f('ix_comentarios_resena_id_entrada_diario'), table_name='comentarios_resena')
    # ### end Alembic commands ###
